Improve Attachment and ClassifiedTaxCategory
num-num/ubl-invoice pull request #57
Opened 2024-01-08 09:45 UTC by bagulho

Allow Attachment to define the content of the file
Add missing accessors for ClassifiedTaxCategory

2024-10-17 17:49 UTC, kouinkouin commented
Hi!
For the new property `Attachement::$fileContent`, do you think that could be better to accept a raw file content, instead of an base64-encoded string?
The name `fileContent` does not suggest the string must be base64-encoded.
What do you think?

2024-10-17 18:06 UTC, kouinkouin requested changes
The property `$fileName` is not used in the class (excepted in get/set).
Maybe, in the method `XmlSerialize`, we could replace the line 167 with:
```diff
-                    'filename' => basename($this->filePath)
+                    'filename' => $filename
```
?

2024-10-17 18:06 UTC, kouinkouin commented on src/Attachment.php
> +                $mimeType = $this->getFileMimeType();
add:
```php
$filename = basename($this->filePath);
```

2024-10-17 18:06 UTC, kouinkouin commented on src/Attachment.php
> +                $mimeType = $this->mimeType;
add:
```php
$filename = $this->filename;
```

2024-10-17 18:09 UTC, kouinkouin commented
Your PR interests me because that is absent of the main branch, so thanks for the PR :-)

2024-11-18 14:30 UTC, brtdv commented
Hi @kouinkouin, thank you for your PR. 

I was going through pull requests today and I've merged something similar earlier today... I think #66 is basically this same functionality, correct? If yes, I'll close this one because I've merged this other one already and the fuctionality is very similar.

2024-11-18 14:51 UTC, Unubius commented
@brtdv Hello, could you please merge the changes from `ClassifiedTaxCategory.php`, I would greatly appreciate it 🙏

2024-11-18 14:52 UTC, brtdv commented
@Unubius, will check, I'm preparing release v1.18 right now and I'll include these

2024-11-18 15:03 UTC, brtdv commented
Hi @kouinkouin, @bagulho, this PR had some overlap with #66. I kept the 'setFileStream' function on `Attachment` from that PR, which basically does the same as `setFileContents` proposed in this PR. This PR also included a setMimeType function which I kept. 

@Unubius all other changes from the PR, such as the changes in `ClassifiedTaxCategory` were included in this PR.

This all will be released in v1.18.

2024-11-18 15:03 UTC, merged